/*
  Warnings:

  - You are about to drop the column `role` on the `Employee` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Employee" DROP COLUMN "role",
ADD COLUMN     "roleId" TEXT,
ADD COLUMN     "specialty" TEXT;

-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "advancesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "advancesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "advancesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "advancesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "anamnesisAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "anamnesisCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "anamnesisDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "anamnesisEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "campaignsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "campaignsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "campaignsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "campaignsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "cashClosureAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsEditCredits" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsNotes" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "clientsViewPhones" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsEditAssist" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commandsViewBilled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commissionsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commissionsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commissionsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "commissionsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "expensesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "expensesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "expensesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "expensesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "financialPanelAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "goalsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "goalsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "goalsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "goalsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "goalsViewAll" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "invoicesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "invoicesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "invoicesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "invoicesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isOwner" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notificationsAll" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "packagesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "packagesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "packagesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "packagesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "productsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "productsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "productsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "productsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "professionalsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "professionalsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "professionalsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "professionalsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "promotionsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "promotionsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "promotionsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "promotionsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "purchasesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "purchasesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "purchasesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "purchasesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receivablesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receivablesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receivablesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receivablesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsClientsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsFinancialAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsInvoicesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsMessagesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsRankingAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsSalesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsScheduleAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reportsStockAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reviewsAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reviewsCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reviewsDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "reviewsEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "salariesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "salariesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "salariesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "salariesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduleAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduleCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduleDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduleEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scheduleViewAll" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "subscriptionSalesAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "subscriptionSalesCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "subscriptionSalesDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "subscriptionSalesEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "suppliersAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "suppliersCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "suppliersDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "suppliersEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "transfersAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "transfersCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "transfersDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "transfersEdit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whatsappAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whatsappCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whatsappDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whatsappEdit" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "Employee_roleId_idx" ON "Employee"("roleId");

-- CreateIndex
CREATE INDEX "Role_salonId_idx" ON "Role"("salonId");

-- CreateIndex
CREATE INDEX "Role_name_idx" ON "Role"("name");

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE SET NULL ON UPDATE CASCADE;
