-- AlterTable
ALTER TABLE "Product" 
ADD COLUMN "professionalPrice" DOUBLE PRECISION,
ADD COLUMN "additionalCostValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "additionalCostType" "ValueType" NOT NULL DEFAULT 'FIXED',
ADD COLUMN "expirationDate" TIMESTAMP(3),
ADD COLUMN "notes" TEXT,
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "isFavorite" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "controlStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "cashbackActive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "cashbackValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cashbackType" "ValueType" NOT NULL DEFAULT 'FIXED';
